sudo: false
language: node_js
node_js:
  - "iojs"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  
before_script:
  - gem update --system
  - gem install compass
  - npm install -g bower grunt-cli
  - bower install
  
matrix:
  allow_failures:
    - node_js: "0.12"
    - node_js: "0.11"
    - node_js: "0.10"
