language: node_js
node_js:
- iojs
- '4.1'
- '4.0'
- '0.12'
- '0.11'
- '0.10'
before_install:
- gem update --system
- gem install bundle
- npm install -g bower grunt-cli
- bundle install
matrix:
  allow_failures:
  - node_js: '0.12'
  - node_js: '0.11'
  - node_js: '0.10'
notifications:
  slack:
    secure: 3yNdqZzxLg/+RnE0w0OknzxWVX3/ZV+pjiRFEIR+AF6495NUayl91V+0V0sjbL1LxuTtrXTr5zVGvvFs4N/DrfrkLRWDK6xXDcxv7OzJ+XkQ1oid1HCHwWu0YQAX4OcynAtstmpPeUnBQIgn+KJ6sCH8pNw9hSAdRkOUmRpMSrSFwlFPDofWfuYnbyclxx+6AveSK73GrwYtI0amBbab91DIOQEULGsADit9S9cfNqCsfkg7QEjGwUsVXoU6ymJXmJJnAw8yzMEpsVA+Gs7s7ZB32weA+Uqk1CF9QiWu40T6ync1Z+l/9836P+sKWHdfQk9j2PTg+c2vOi4AW8jvt7iuV5KHsl5dHGu3L80GZF06d3Wvwh+SnBaxPZZ+d131kQBv1TmgFjnLjNXZCiHdz99dZqtT75vwvDS5sZQabqIAmrksTp46U8DI0FbfDhkJnuwnrzc3v2CPW7V+tv80F7WmHw2ZZ4yIGPc8KXyO8tTXDSS+jm3iAFK9bOBLonAhr8OMoSuE0dETrhNvpIEaLDNMue7M82iy6kz0C/Da59NZq/ztgQYQjDTWAJw3nO9GjxgeHi6D5YiIua3ylmo0PfC4jm2HyQEBqDiqfyoxKEUjhC/elpPuaORHVgO/6YGg4Yn+2iFaz6YTr5VmAY9FxB/8HYiw7hL5f+ZQsGzF/to=

